// Generated by cazmac/Tools/GenerateRig.swift from simple-opencat-reference.urdf.
// Edit the URDF source and regenerate rather than hand-editing rig entries.

import Foundation
import simd

enum CazRigShape: String {
    case box
    case capsule
    case ellipse
    case triangle
}

enum CazRigColorSlot: String {
    case accent
    case body
    case dark
    case joint
    case mesh
    case paw
    case sensor
    case shell
}

struct CazRigLink {
    let name: String
    let shape: CazRigShape
    let center: SIMD2<Float>
    let size: SIMD2<Float>
    let colorSlot: CazRigColorSlot
}

struct CazRigJoint {
    let name: String
    let parent: String
    let child: String
    let cazJointIndex: Int
    let origin: SIMD2<Float>
    let axis: SIMD2<Float>
    let lower: Float
    let upper: Float
}

struct CazRigDefinition {
    let name: String
    let source: String
    let optionalMeshesEnabled: Bool
    let links: [CazRigLink]
    let joints: [CazRigJoint]

    func link(named name: String) -> CazRigLink? {
        links.first { $0.name == name }
    }

    func joint(named name: String) -> CazRigJoint? {
        joints.first { $0.name == name }
    }
}

enum CazRigGenerated {
    static let definition = CazRigDefinition(
        name: "caz_opencat_simple_reference",
        source: "cazmac/Assets/ThirdParty/OpenCat/simple-opencat-reference.urdf",
        optionalMeshesEnabled: false,
        links: [
        CazRigLink(name: "torso", shape: .ellipse, center: SIMD2<Float>(0, 0), size: SIMD2<Float>(0.68, 0.24), colorSlot: .body),
        CazRigLink(name: "chest", shape: .ellipse, center: SIMD2<Float>(-0.23, 0.04), size: SIMD2<Float>(0.24, 0.16), colorSlot: .shell),
        CazRigLink(name: "neck", shape: .capsule, center: SIMD2<Float>(-0.36, 0.08), size: SIMD2<Float>(0.18, 0.08), colorSlot: .dark),
        CazRigLink(name: "head", shape: .ellipse, center: SIMD2<Float>(-0.50, 0.11), size: SIMD2<Float>(0.28, 0.22), colorSlot: .shell),
        CazRigLink(name: "left-ear", shape: .triangle, center: SIMD2<Float>(-0.59, 0.26), size: SIMD2<Float>(0.12, 0.18), colorSlot: .dark),
        CazRigLink(name: "right-ear", shape: .triangle, center: SIMD2<Float>(-0.43, 0.26), size: SIMD2<Float>(0.12, 0.18), colorSlot: .dark),
        CazRigLink(name: "left-front-upper-leg", shape: .capsule, center: SIMD2<Float>(-0.23, -0.19), size: SIMD2<Float>(0.06, 0.24), colorSlot: .dark),
        CazRigLink(name: "left-front-lower-leg", shape: .capsule, center: SIMD2<Float>(-0.25, -0.42), size: SIMD2<Float>(0.05, 0.24), colorSlot: .dark),
        CazRigLink(name: "right-front-upper-leg", shape: .capsule, center: SIMD2<Float>(-0.10, -0.19), size: SIMD2<Float>(0.06, 0.24), colorSlot: .dark),
        CazRigLink(name: "right-front-lower-leg", shape: .capsule, center: SIMD2<Float>(-0.08, -0.42), size: SIMD2<Float>(0.05, 0.24), colorSlot: .dark),
        CazRigLink(name: "left-rear-upper-leg", shape: .capsule, center: SIMD2<Float>(0.14, -0.19), size: SIMD2<Float>(0.07, 0.25), colorSlot: .dark),
        CazRigLink(name: "left-rear-lower-leg", shape: .capsule, center: SIMD2<Float>(0.12, -0.43), size: SIMD2<Float>(0.055, 0.25), colorSlot: .dark),
        CazRigLink(name: "right-rear-upper-leg", shape: .capsule, center: SIMD2<Float>(0.29, -0.19), size: SIMD2<Float>(0.07, 0.25), colorSlot: .dark),
        CazRigLink(name: "right-rear-lower-leg", shape: .capsule, center: SIMD2<Float>(0.31, -0.43), size: SIMD2<Float>(0.055, 0.25), colorSlot: .dark),
        CazRigLink(name: "tail-base", shape: .capsule, center: SIMD2<Float>(0.43, 0.06), size: SIMD2<Float>(0.24, 0.06), colorSlot: .dark),
        CazRigLink(name: "tail-tip", shape: .capsule, center: SIMD2<Float>(0.64, 0.08), size: SIMD2<Float>(0.24, 0.045), colorSlot: .dark)
        ],
        joints: [
        CazRigJoint(name: "head-yaw", parent: "neck", child: "head", cazJointIndex: 0, origin: SIMD2<Float>(-0.38, 0.09), axis: SIMD2<Float>(0, 1), lower: -0.75, upper: 0.75),
        CazRigJoint(name: "head-pitch", parent: "neck", child: "head", cazJointIndex: 1, origin: SIMD2<Float>(-0.40, 0.10), axis: SIMD2<Float>(1, 0), lower: -0.50, upper: 0.50),
        CazRigJoint(name: "left-front-shoulder", parent: "torso", child: "left-front-upper-leg", cazJointIndex: 2, origin: SIMD2<Float>(-0.23, -0.04), axis: SIMD2<Float>(1, 0), lower: -0.90, upper: 0.90),
        CazRigJoint(name: "right-front-shoulder", parent: "torso", child: "right-front-upper-leg", cazJointIndex: 3, origin: SIMD2<Float>(-0.10, -0.04), axis: SIMD2<Float>(1, 0), lower: -0.90, upper: 0.90),
        CazRigJoint(name: "left-rear-hip", parent: "torso", child: "left-rear-upper-leg", cazJointIndex: 4, origin: SIMD2<Float>(0.14, -0.04), axis: SIMD2<Float>(1, 0), lower: -0.90, upper: 0.90),
        CazRigJoint(name: "right-rear-hip", parent: "torso", child: "right-rear-upper-leg", cazJointIndex: 5, origin: SIMD2<Float>(0.29, -0.04), axis: SIMD2<Float>(1, 0), lower: -0.90, upper: 0.90),
        CazRigJoint(name: "tail-base", parent: "torso", child: "tail-base", cazJointIndex: 6, origin: SIMD2<Float>(0.38, 0.06), axis: SIMD2<Float>(0, 1), lower: -1.10, upper: 1.10),
        CazRigJoint(name: "tail-tip", parent: "tail-base", child: "tail-tip", cazJointIndex: 7, origin: SIMD2<Float>(0.58, 0.07), axis: SIMD2<Float>(0, 1), lower: -1.10, upper: 1.10),
        CazRigJoint(name: "spine-height", parent: "world", child: "torso", cazJointIndex: 8, origin: SIMD2<Float>(0, 0), axis: SIMD2<Float>(0, 1), lower: -0.09, upper: 0.09),
        CazRigJoint(name: "spine-curve", parent: "torso", child: "chest", cazJointIndex: 9, origin: SIMD2<Float>(-0.14, 0.03), axis: SIMD2<Float>(1, 0), lower: -0.55, upper: 0.55),
        CazRigJoint(name: "left-knee", parent: "left-rear-upper-leg", child: "left-rear-lower-leg", cazJointIndex: 10, origin: SIMD2<Float>(0.14, -0.30), axis: SIMD2<Float>(1, 0), lower: -1.10, upper: 1.10),
        CazRigJoint(name: "right-knee", parent: "right-rear-upper-leg", child: "right-rear-lower-leg", cazJointIndex: 11, origin: SIMD2<Float>(0.29, -0.30), axis: SIMD2<Float>(1, 0), lower: -1.10, upper: 1.10),
        CazRigJoint(name: "left-elbow", parent: "left-front-upper-leg", child: "left-front-lower-leg", cazJointIndex: 12, origin: SIMD2<Float>(-0.23, -0.29), axis: SIMD2<Float>(1, 0), lower: -1.10, upper: 1.10),
        CazRigJoint(name: "right-elbow", parent: "right-front-upper-leg", child: "right-front-lower-leg", cazJointIndex: 13, origin: SIMD2<Float>(-0.10, -0.29), axis: SIMD2<Float>(1, 0), lower: -1.10, upper: 1.10),
        CazRigJoint(name: "paw-spread", parent: "torso", child: "torso", cazJointIndex: 14, origin: SIMD2<Float>(0, -0.53), axis: SIMD2<Float>(1, 0), lower: -0.05, upper: 0.05),
        CazRigJoint(name: "body-roll", parent: "world", child: "torso", cazJointIndex: 15, origin: SIMD2<Float>(0, 0), axis: SIMD2<Float>(0, 0), lower: -0.40, upper: 0.40)
        ]
    )
}
