#!/usr/bin/env swift

import Foundation

struct Link {
    var name: String
    var origin = "0 0"
    var size = "0.10 0.10"
    var shape = "box"
    var color = "body"
}

struct Joint {
    var name: String
    var parent = ""
    var child = ""
    var origin = "0 0"
    var axis = "0 1"
    var lower = "0"
    var upper = "0"
    var cazIndex = -1
}

func attr(_ name: String, in text: String) -> String? {
    guard let start = text.range(of: "\(name)=\"") else { return nil }
    let rest = text[start.upperBound...]
    guard let end = rest.firstIndex(of: "\"") else { return nil }
    return String(rest[..<end])
}

func tagAttr(_ tag: String, _ name: String, in text: String) -> String? {
    guard let start = text.range(of: tag) else { return nil }
    return attr(name, in: String(text[start.lowerBound...]))
}

func xy(_ xyz: String) -> String {
    let parts = xyz.split(separator: " ")
    guard parts.count >= 2 else { return "0, 0" }
    return "\(parts[0]), \(parts[1])"
}

func swiftString(_ text: String) -> String {
    text.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
}

guard CommandLine.arguments.count == 3 else {
    FileHandle.standardError.write(Data("usage: swift GenerateRig.swift input.urdf output.swift\n".utf8))
    exit(2)
}

let inputURL = URL(fileURLWithPath: CommandLine.arguments[1])
let outputURL = URL(fileURLWithPath: CommandLine.arguments[2])
let lines = try String(contentsOf: inputURL, encoding: .utf8).split(separator: "\n", omittingEmptySubsequences: false).map(String.init)

var links: [Link] = []
var joints: [Joint] = []
var currentLink: Link?
var currentJoint: Joint?

for rawLine in lines {
    let line = rawLine.trimmingCharacters(in: .whitespaces)
    if line.hasPrefix("<link "), let name = attr("name", in: line) {
        currentLink = Link(name: name)
    } else if line.hasPrefix("</link>"), let link = currentLink {
        links.append(link)
        currentLink = nil
    } else if line.hasPrefix("<joint "), let name = attr("name", in: line) {
        var joint = Joint(name: name)
        joint.parent = tagAttr("<parent", "link", in: line) ?? ""
        joint.child = tagAttr("<child", "link", in: line) ?? ""
        joint.origin = tagAttr("<origin", "xyz", in: line) ?? "0 0"
        joint.axis = tagAttr("<axis", "xyz", in: line) ?? "0 1"
        joint.lower = tagAttr("<limit", "lower", in: line) ?? "0"
        joint.upper = tagAttr("<limit", "upper", in: line) ?? "0"
        if let index = tagAttr("<caz:map", "index", in: line), let value = Int(index) {
            joint.cazIndex = value
        }
        if line.contains("</joint>") {
            joints.append(joint)
        } else {
            currentJoint = joint
        }
    } else if line.hasPrefix("</joint>"), let joint = currentJoint {
        joints.append(joint)
        currentJoint = nil
    } else if line.hasPrefix("<origin "), let origin = attr("xyz", in: line) {
        if currentJoint != nil {
            currentJoint?.origin = origin
        } else {
            currentLink?.origin = origin
        }
    } else if line.contains("<box "), let size = attr("size", in: line) {
        currentLink?.size = size
    } else if line.contains("<caz:render ") {
        currentLink?.shape = attr("shape", in: line) ?? currentLink?.shape ?? "box"
        currentLink?.color = attr("color", in: line) ?? currentLink?.color ?? "body"
    } else if line.contains("<parent "), let parent = attr("link", in: line) {
        currentJoint?.parent = parent
    } else if line.contains("<child "), let child = attr("link", in: line) {
        currentJoint?.child = child
    } else if line.contains("<axis "), let axis = attr("xyz", in: line) {
        currentJoint?.axis = axis
    } else if line.contains("<limit ") {
        currentJoint?.lower = attr("lower", in: line) ?? "0"
        currentJoint?.upper = attr("upper", in: line) ?? "0"
    } else if line.contains("<caz:map "), let index = attr("index", in: line), let value = Int(index) {
        currentJoint?.cazIndex = value
    }
}

let linkRows = links.map { link -> String in
    "        CazRigLink(name: \"\(swiftString(link.name))\", shape: .\(link.shape), center: SIMD2<Float>(\(xy(link.origin))), size: SIMD2<Float>(\(xy(link.size))), colorSlot: .\(link.color))"
}.joined(separator: ",\n")

let jointRows = joints.map { joint -> String in
    "        CazRigJoint(name: \"\(swiftString(joint.name))\", parent: \"\(swiftString(joint.parent))\", child: \"\(swiftString(joint.child))\", cazJointIndex: \(joint.cazIndex), origin: SIMD2<Float>(\(xy(joint.origin))), axis: SIMD2<Float>(\(xy(joint.axis))), lower: \(joint.lower), upper: \(joint.upper))"
}.joined(separator: ",\n")

let output = """
// Generated by cazmac/Tools/GenerateRig.swift from \(inputURL.lastPathComponent).
// Edit the URDF source and regenerate rather than hand-editing rig entries.

import Foundation
import simd

enum CazRigShape: String {
    case box
    case capsule
    case ellipse
    case triangle
}

enum CazRigColorSlot: String {
    case accent
    case body
    case dark
    case joint
    case mesh
    case paw
    case sensor
    case shell
}

struct CazRigLink {
    let name: String
    let shape: CazRigShape
    let center: SIMD2<Float>
    let size: SIMD2<Float>
    let colorSlot: CazRigColorSlot
}

struct CazRigJoint {
    let name: String
    let parent: String
    let child: String
    let cazJointIndex: Int
    let origin: SIMD2<Float>
    let axis: SIMD2<Float>
    let lower: Float
    let upper: Float
}

struct CazRigDefinition {
    let name: String
    let source: String
    let optionalMeshesEnabled: Bool
    let links: [CazRigLink]
    let joints: [CazRigJoint]

    func link(named name: String) -> CazRigLink? {
        links.first { $0.name == name }
    }

    func joint(named name: String) -> CazRigJoint? {
        joints.first { $0.name == name }
    }
}

enum CazRigGenerated {
    static let definition = CazRigDefinition(
        name: "caz_opencat_simple_reference",
        source: "cazmac/Assets/ThirdParty/OpenCat/\(inputURL.lastPathComponent)",
        optionalMeshesEnabled: false,
        links: [
\(linkRows)
        ],
        joints: [
\(jointRows)
        ]
    )
}
"""

try (output + "\n").write(to: outputURL, atomically: true, encoding: .utf8)
